const message = {
  UPDATE_SUCCESSFULLY: 'UPDATE_SUCCESSFULLY',
  CREATE_SUCCESSFULLY: 'CREATE_SUCCESSFULLY',
  GET_SUCCESSFULLY: 'GET_SUCCESSFULLY',
  DELETE_SUCCESSFULLY: 'DELETE_SUCCESSFULLY',
};

export default message;
